import {
  boolean,
  char,
  int,
  json,
  mediumtext,
  mysqlTable,
  text,
  timestamp,
  varchar,
  decimal,
} from "drizzle-orm/mysql-core"

const id = () => char("id", { length: 36 }).primaryKey().notNull()
const timestamps = {
  created_at: timestamp("created_at").defaultNow().notNull(),
}

export const classes = mysqlTable("classes", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  description: text("description"),
  hit_die: int("hit_die").notNull().default(8),
  primary_ability: json("primary_ability").$type<string[]>(),
  saving_throws: json("saving_throws").$type<string[]>(),
  armor_proficiencies: json("armor_proficiencies").$type<string[]>(),
  weapon_proficiencies: json("weapon_proficiencies").$type<string[]>(),
  skill_choices: json("skill_choices").$type<{ count: number; options: string[] } | null>(),
  starting_equipment: json("starting_equipment"),
  starting_equipment_groups: json("starting_equipment_groups"),
  starting_gold: int("starting_gold").default(0),
  features: json("features").$type<unknown[]>().default([]),
  spellcasting: json("spellcasting"),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const subclasses = mysqlTable("subclasses", {
  id: id(),
  class_id: char("class_id", { length: 36 }),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  features: json("features").$type<unknown[]>().default([]),
  spellcasting: json("spellcasting"),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const species = mysqlTable("species", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  description: text("description"),
  speed: json("speed"),
  size: varchar("size", { length: 32 }),
  creature_type: varchar("creature_type", { length: 64 }).default("Humanoid"),
  traits: json("traits").$type<unknown[]>().default([]),
  characteristics: json("characteristics").$type<unknown[]>().default([]),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const backgrounds = mysqlTable("backgrounds", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  description: text("description"),
  ability_bonuses: json("ability_bonuses"),
  skill_proficiencies: json("skill_proficiencies").$type<string[]>(),
  tool_proficiencies: json("tool_proficiencies").$type<string[]>(),
  proficiencies: json("proficiencies").$type<import("@/lib/compendium/background-proficiencies").BackgroundProficiencies>(),
  feat_granted: varchar("feat_granted", { length: 255 }),
  starting_gold: int("starting_gold"),
  starting_equipment: json("starting_equipment"),
  equipment: json("equipment"),
  feature: json("feature"),
  grants_spells: boolean("grants_spells").notNull().default(false),
  granted_spells: json("granted_spells").$type<Record<string, string[]>>(),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const spells = mysqlTable("spells", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  level: int("level").notNull().default(0),
  school: varchar("school", { length: 64 }).notNull(),
  casting_time: varchar("casting_time", { length: 128 }),
  range: varchar("range", { length: 128 }),
  components: json("components").$type<string[]>(),
  material: text("material"),
  duration: varchar("duration", { length: 128 }),
  concentration: boolean("concentration").notNull().default(false),
  ritual: boolean("ritual").notNull().default(false),
  description: text("description"),
  higher_levels: text("higher_levels"),
  classes: json("classes").$type<string[]>(),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const feats = mysqlTable("feats", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  description: text("description"),
  category: varchar("category", { length: 64 }),
  level_requirement: int("level_requirement"),
  prerequisite: text("prerequisite"),
  prerequisite_feat_ids: json("prerequisite_feat_ids").$type<string[]>(),
  prerequisite_class_ids: json("prerequisite_class_ids").$type<string[]>(),
  prerequisite_species_ids: json("prerequisite_species_ids").$type<string[]>(),
  prerequisite_background_ids: json("prerequisite_background_ids").$type<string[]>(),
  benefits: json("benefits"),
  repeatable: boolean("repeatable").notNull().default(false),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const equipment = mysqlTable("equipment", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  category: varchar("category", { length: 128 }).notNull(),
  subcategory: varchar("subcategory", { length: 128 }),
  cost: json("cost"),
  weight: decimal("weight", { precision: 10, scale: 2 }),
  properties: json("properties"),
  description: text("description"),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  ...timestamps,
})

export const customAbilities = mysqlTable("custom_abilities", {
  id: id(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  characteristics: json("characteristics").$type<unknown[]>().default([]),
  prerequisites: text("prerequisites"),
  attached_to_type: varchar("attached_to_type", { length: 64 }),
  attached_to_id: varchar("attached_to_id", { length: 128 }),
  uses: json("uses"),
  show_in_builder: boolean("show_in_builder").notNull().default(true),
  icon: varchar("icon", { length: 255 }),
  source: varchar("source", { length: 64 }).notNull().default("Custom"),
  creator_url: varchar("creator_url", { length: 512 }),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
})

export const characters = mysqlTable("characters", {
  id: id(),
  local_id: varchar("local_id", { length: 64 }),
  name: varchar("name", { length: 255 }).notNull().default("Unnamed"),
  level: int("level").notNull().default(1),
  experience: int("experience").notNull().default(0),
  class_id: char("class_id", { length: 36 }),
  subclass_id: char("subclass_id", { length: 36 }),
  species_id: char("species_id", { length: 36 }),
  background_id: char("background_id", { length: 36 }),
  strength: int("strength").notNull().default(10),
  dexterity: int("dexterity").notNull().default(10),
  constitution: int("constitution").notNull().default(10),
  intelligence: int("intelligence").notNull().default(10),
  wisdom: int("wisdom").notNull().default(10),
  charisma: int("charisma").notNull().default(10),
  alignment: varchar("alignment", { length: 64 }),
  personality_traits: text("personality_traits"),
  ideals: text("ideals"),
  bonds: text("bonds"),
  flaws: text("flaws"),
  backstory: text("backstory"),
  appearance: json("appearance"),
  portrait_url: mediumtext("portrait_url"),
  banner_url: mediumtext("banner_url"),
  asi_allocations: json("asi_allocations").$type<Record<string, Record<string, number>>>(),
  proficiency_bonus: int("proficiency_bonus").notNull().default(2),
  hit_points: int("hit_points"),
  hit_point_max: int("hit_point_max"),
  armor_class: int("armor_class"),
  initiative: int("initiative"),
  speed: int("speed"),
  skill_proficiencies: json("skill_proficiencies").$type<string[]>(),
  skill_expertise: json("skill_expertise").$type<string[]>(),
  tool_proficiencies: json("tool_proficiencies").$type<string[]>(),
  weapon_proficiencies: json("weapon_proficiencies").$type<string[]>(),
  armor_proficiencies: json("armor_proficiencies").$type<string[]>(),
  languages: json("languages").$type<string[]>(),
  equipment_ids: json("equipment_ids").$type<string[]>().default([]),
  spell_ids: json("spell_ids").$type<string[]>().default([]),
  feat_ids: json("feat_ids").$type<string[]>().default([]),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
})

export const tableMap = {
  classes,
  subclasses,
  species,
  backgrounds,
  spells,
  feats,
  equipment,
  custom_abilities: customAbilities,
  characters,
} as const

export type TableName = keyof typeof tableMap
