import {
  maybeFilterDefaultCardImageUrl,
  type DefaultCardImageAvailability,
} from "@/lib/compendium/available-card-art"
import { withBasePath } from "@/lib/config/deploy-mode"

const spellCardImage = (slug: string) => withBasePath(`/images/compendium/spells/${slug}.png`)

/** Slug for bundled spell card art filenames under public/images/compendium/spells/. */
export function spellNameToCardImageSlug(spellName: string): string {
  return spellName
    .trim()
    .toLowerCase()
    // ASCII + typographic apostrophes (Kibbles uses U+2019 in names like Trary’s …)
    .replace(/['\u2019]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

/**
 * Display-name → output slug when the filename differs from a naive kebab-case of the name
 * (typos in masters, plural/singular import variants, shortened titles).
 */
const SPELL_CARD_IMAGE_SLUG_OVERRIDES: Record<string, string> = {
  "Dancing Objects (Animate Object)": "dancing-object-animate-object",
}

/** Spell names with bundled card art (SRD and homebrew-ready name matching). */
export const BUNDLED_SPELL_CARD_IMAGE_NAMES = [
  "Aberrant Spirit",
  "Acid Arrow",
  "Acid Splash",
  "Aether Lance",
  "Aether Storm",
  "Aid",
  "Alarm",
  "Alter Self",
  "Alustriels Mooncloak",
  "Animal Friendship",
  "Animal Messenger",
  "Animal Shapes",
  "Animate Dead",
  "Animate Objects",
  "Antilife Shell",
  "Antimagic Field",
  "Antipathy/Sympathy",
  "Arc Blade",
  "Arcane Ablation",
  "Arcane Eye",
  "Arcane Gate",
  "Arcane Hand",
  "Arcane Infusion",
  "Arcane Lock",
  "Arcane Sword",
  "Arcane Vigor",
  "Arcane Weapon",
  "Arcanist's Magic Aura",
  "Arctic Breath",
  "Armor Of Agathys",
  "Arms Of Hadar",
  "Astral Projection",
  "Astral Projection 02 Ship",
  "Augury",
  "Aura Of Evasion",
  "Aura of Life",
  "Aura Of Purity",
  "Aura Of Vitality",
  "Awaken",
  "Awaken Rope",
  "Backlash",
  "Bane",
  "Banishing Smite",
  "Banishment",
  "Barkskin",
  "Battle Familiar",
  "Beacon of Hope",
  "Beam of Annihilation",
  "Befuddlement",
  "Bestial Spirit",
  "Bestow Curse",
  "Black Tentacles",
  "Blade Barrier",
  "Blade Of Disaster",
  "Blade Ward",
  "Bless",
  "Blight",
  "Blinding Smite",
  "Blindness/Deafness",
  "Blink",
  "Blur",
  "Bond Item",
  "Booming Blade",
  "Burning Blade",
  "Burning Hands",
  "Cacophonic Shield",
  "Call Lightning",
  "Calm Emotions",
  "Candy Blast",
  "Card Trick",
  "Catnap",
  "Caustic Brew",
  "Celestial Spirit",
  "Ceremony",
  "Chain Lightning",
  "Chaos Bolt",
  "Charm Monster",
  "Charm Person",
  "Cheat",
  "Chill Touch",
  "Chromatic Orb",
  "Circle of Death",
  "Circle Of Power",
  "Clairvoyance",
  "Clay Touch",
  "Clone",
  "Cloud Of Daggers",
  "Cloudkill",
  "Cold Snap",
  "Color Spray",
  "Command",
  "Commune",
  "Commune with Nature",
  "Compelled Duel",
  "Compelled Query",
  "Comprehend Languages",
  "Compulsion",
  "Concealed Shot",
  "Cone of Cold",
  "Confusion",
  "Conjure Animals",
  "Conjure Barrage",
  "Conjure Celestial",
  "Conjure Constructs",
  "Conjure Elemental",
  "Conjure Fey",
  "Conjure Minor Elementals",
  "Conjure Volley",
  "Conjure Woodland Beings",
  "Construct Spirit",
  "Contact Other Plane",
  "Contagion",
  "Contingency",
  "Continual Flame",
  "Control Flames",
  "Control Water",
  "Control Weather",
  "Cordon Of Arrows",
  "Counterspell",
  "Crackle",
  "Create Bonfire",
  "Create Food and Water",
  "Create or Destroy Water",
  "Create Undead",
  "Creation",
  "Crippling Agony",
  "Crown Of Madness",
  "Crusaders Mantle",
  "Cryptogram",
  "Cure Wounds",
  "Dancing Lights",
  "Dancing Object (Animate Object)",
  "Dancing Objects (Animate Object)",
  "Darkvision",
  "Daylight",
  "Death Armor",
  "Death Ward",
  "Delayed Blast Fireball",
  "Delve Mind",
  "Demiplane",
  "Deryans Helpful Homunculi",
  "Destructive Wave",
  "Detect Evil and Good",
  "Detect Poison and Disease",
  "Detonate",
  "Devouring Darkness",
  "Dig",
  "Dimension Cutter",
  "Dimension Door",
  "Dinosaur Spirit",
  "Dirge",
  "Disguise Self",
  "Disintegrate",
  "Disorient",
  "Dispel Construct",
  "Dispel Evil and Good",
  "Dispel Magic",
  "Disruptive Tune",
  "Dissonant Whispers",
  "Distorted Distance",
  "Divide Self",
  "Divination",
  "Divine Favor",
  "Divine Smite",
  "Divine Word",
  "Dominate Beast",
  "Dominate Monster",
  "Dominate Person",
  "Doomtide",
  "Dragon Spirit",
  "Dragon's Breath",
  "Dream",
  "Druidcraft",
  "Dueling Ground",
  "Earthquake",
  "Eldritch Blast",
  "Eldritch Orb",
  "Electrocute",
  "Elemental Spirit",
  "Elemental Weapon",
  "Elementalism",
  "Elminsters Effulgent Spheres",
  "Elminsters Elusion",
  "Enemies Abound",
  "Enervation",
  "Enlarge/Reduce",
  "Ensnaring Strike",
  "Entangle",
  "Enthrall",
  "Entomb",
  "Entrancing Mirrors",
  "Etherealness",
  "Expeditious Retreat",
  "Extra",
  "Eyebite",
  "Fabricate",
  "Faerie Fire",
  "Faithful Hound",
  "Fall",
  "False Life",
  "Fear",
  "Feather Fall",
  "Feign Death",
  "Festering Blast",
  "Fey Spirit",
  "Fiendish Spirit",
  "Find Familiar",
  "Find Steed",
  "Find the Path",
  "Find Traps",
  "Finger Guns",
  "Finger of Death",
  "Fire Bolt",
  "Fire Cyclone",
  "Fire Shield",
  "Fire Storm",
  "Fireball",
  "Fireburst Mine",
  "Fissure",
  "Flame Blade",
  "Flame Strike",
  "Flaming Sphere",
  "Flash Freeze",
  "Flesh to Stone",
  "Flicker",
  "Flickering Strikes",
  "Fling",
  "Floating Disk",
  "Fly",
  "Fog Cloud",
  "Forbiddance",
  "Force Buckler",
  "Force Dart",
  "Force Weapon",
  "Forcecage",
  "Foresight",
  "Fount Of Moonlight",
  "Fractured Awareness",
  "Freedom of Movement",
  "Freezing Sphere",
  "Friends",
  "Frighten",
  "Frigid Blade",
  "Frostbite",
  "Future Insight",
  "Gaseous Form",
  "Gate",
  "Geas",
  "Gentle Repose",
  "Giant Insect",
  "Glibness",
  "Glimpse the Future",
  "Globe of Invulnerability",
  "Glyph of Warding",
  "Goodberry",
  "Grasping Vine",
  "Grave Ground",
  "Grease",
  "Greater Invisibility",
  "Greater Restoration",
  "Green-Flame Blade",
  "Guardian of Faith",
  "Guards and Wards",
  "Guidance",
  "Guiding Bolt",
  "Gust",
  "Hail Of Thorns",
  "Hallow",
  "Hallucinatory Terrain",
  "Harm",
  "Haste",
  "Heal",
  "Healing Word",
  "Heat Metal",
  "Hellish Rebuke",
  "Heroes' Feast",
  "Heroism",
  "Hex",
  "Hex:abate",
  "Hex:apathy",
  "Hex:bleeding",
  "Hex:charm",
  "Hex:disorient",
  "Hex:doomward",
  "Hex:duplicity",
  "Hex:evil Eye",
  "Hex:fortune",
  "Hex:garble",
  "Hex:hobble",
  "Hex:mire",
  "Hex:misfortune",
  "Hex:obfuscate",
  "Hex:peacebond",
  "Hex:pox",
  "Hex:ruin",
  "Hex:stupor",
  "Hex:tremors",
  "Hex:vanish",
  "Hex:ward",
  "Hideous Laughter",
  "Hindsight",
  "Hocuspocus",
  "Hold Monster",
  "Hold Person",
  "Holy Aura",
  "Holy Star Of Mystra",
  "Hunter's Mark",
  "Hypnotic Pattern",
  "Ice Knife",
  "Ice Spike",
  "Ice Storm",
  "Ichorous Blood",
  "Identify",
  "Illusory Dragon",
  "Illusory Script",
  "Imbue Luck",
  "Impact",
  "Imprisonment",
  "Incendiary Cloud",
  "Infestation",
  "Inflict Doubt",
  "Inflict Wounds",
  "Inner World",
  "Insect Plague",
  "Instant Summons",
  "Intellect Fortress",
  "Invest Life",
  "Invested Competency",
  "Invisibility",
  "Invulnerability",
  "Iron Body",
  "Irresistible Dance",
  "Jallarzis Storm Of Radiance",
  "Jump",
  "Jumping Jolt",
  "Killing Curse",
  "Knock",
  "Laerals Silver Lance",
  "Launch Object",
  "Leave No Trace",
  "Legend Lore",
  "Legendary Libation",
  "Leomunds Tiny Chest",
  "Lesser Restoration",
  "Life Transference",
  "Light",
  "Lightning Bolt",
  "Lightning Charged",
  "Lightning Lure",
  "Lightning Ring",
  "Lightning Surge",
  "Lightning Tendril",
  "Locate Animals or Plants",
  "Locate Creature",
  "Longstrider",
  "Mage Armor",
  "Mage Hand",
  "Magic Circle",
  "Magic Daggers",
  "Magic Jar",
  "Magic Missile",
  "Magic Mouth",
  "Magic Stone",
  "Magic Weapon",
  "Magnificent Mansion",
  "Major Image",
  "Mass Cure Wounds",
  "Mass Heal",
  "Mass Healing Word",
  "Mass Suggestion",
  "Maxamillions Earthen Grasp",
  "Maze",
  "Meld into Stone",
  "Melting Glob",
  "Mending",
  "Message",
  "Meteor Swarm",
  "Mind Blank",
  "Mind Blast",
  "Mind Sliver",
  "Minor Illusion",
  "Minor Lifesteal",
  "Mirage Arcane",
  "Mirror Image",
  "Mislead",
  "Misty Step",
  "Modify Memory",
  "Mold Earth",
  "Moment Of Prescience",
  "Moonbeam",
  "Mordenkainens Lucubration",
  "Move Earth",
  "Mutate",
  "Negative Energy Flood",
  "Nondetection",
  "Nullify Effect",
  "Orbital Stones",
  "Other Spell",
  "Otherworldly Steed",
  "Pass without Trace",
  "Passwall",
  "Path",
  "Phantasmal Force",
  "Phantasmal Killer",
  "Phantom Grapnel",
  "Phantom Steed",
  "Planar Ally",
  "Planar Binding",
  "Plane Shift",
  "Plant Growth",
  "Plant Spirit",
  "Poison Spray",
  "Polymorph",
  "Power Word Fortify",
  "Power Word Heal",
  "Power Word Kill",
  "Power Word Pain",
  "Power Word Stun",
  "Prayer of Healing",
  "Prestidigitation",
  "Primal Savagery",
  "Prismatic Spray",
  "Prismatic Wall",
  "Prismatic Weapon",
  "Private Sanctum",
  "Produce Flame",
  "Programmed Illusion",
  "Project Image",
  "Protection from Energy",
  "Protection from Evil and Good",
  "Protection from Poison",
  "Psychic",
  "Psychic Drain",
  "Purify Food and Drink",
  "Pyrotechnics",
  "Quickstep",
  "Rain of Spiders",
  "Raise Dead",
  "Ray of Enfeeblement",
  "Ray of Frost",
  "Ray of Sickness",
  "Regenerate",
  "Reincarnate",
  "Remove Curse",
  "Repair",
  "Resilient Sphere",
  "Resistance",
  "Resurrection",
  "Returning Weapon",
  "Reverse Gravity",
  "Revivify",
  "Reweave Fate Original",
  "Rope Trick",
  "Sacred Flame",
  "Sanctuary",
  "Scorching Ray",
  "Scrying",
  "Scurry",
  "Searing Smite",
  "Secret Chest",
  "See Invisibility",
  "Seeking Projectile",
  "Seeming",
  "Sending",
  "Sequester",
  "Shape Water",
  "Shapechange",
  "Shatter",
  "Shield",
  "Shield of Faith",
  "Shillelagh",
  "Shining Smite",
  "Shocking Grasp",
  "Shockwave",
  "Shriek",
  "Silence",
  "Silent Image",
  "Silvery Barbs",
  "Simbuls Synostodweomer",
  "Simulacrum",
  "Sky Burst",
  "Sleep",
  "Sleet Storm",
  "Slow",
  "Smite",
  "Snare",
  "Snowball Swarm",
  "Solar Wind",
  "Songals Elemental Suffusion",
  "Sonic Pulse",
  "Sorcerous Burst",
  "Spare the Dying",
  "Spark Of Life",
  "Speak with Animals",
  "Speak with Dead",
  "Speak with Plants",
  "Spectral Weapon",
  "Spellfire Flare",
  "Spellfire Storm",
  "Spider Climb",
  "Spike Growth",
  "Spirit Guardians",
  "Spirit Lantern",
  "Spirit Shroud",
  "Springheel",
  "Staggering Smite",
  "Starry Wisp",
  "Static Field",
  "Stinking Cloud",
  "Stone Shape",
  "Stoneskin",
  "Storm of Vengeance",
  "Suggestion",
  "Sulfuric Smoke",
  "Summon Aberration",
  "Summon Beast",
  "Summon Celestial",
  "Summon Construct",
  "Summon Dinosaur",
  "Summon Dragon",
  "Summon Elemental",
  "Summon Fey",
  "Summon Fiend",
  "Summon Plant",
  "Summon Undead",
  "Sunbeam",
  "Sunburst",
  "Swift Quiver",
  "Sword Burst",
  "Sylunes Viper",
  "Symbol",
  "Symbol Discord",
  "Symbol Sleep",
  "Synaptic Static",
  "Telekinesis",
  "Telepathic Bond",
  "Telepathy",
  "Teleport",
  "Teleportation Circle",
  "Thaumaturgy",
  "Thorn Whip",
  "Thunder Punch",
  "Thunderburst Mine",
  "Thunderclap",
  "Thunderous Echo",
  "Thunderous Smite",
  "Thunderwave",
  "Time Stop",
  "Tiny Hut",
  "Tiny Servant",
  "Toll the Dead",
  "Tongues",
  "Transfix",
  "Translocating Shot",
  "Transport via Plants",
  "Trary’s Terrific Transposition",
  "Tree Stride",
  "True Polymorph",
  "True Resurrection",
  "True Seeing",
  "True Strike",
  "Tsunami",
  "Turbulent Warp",
  "Unburden",
  "Uncertain Footing",
  "Undead Spirit",
  "Unlocked Potential",
  "Unseen Servant",
  "Vampiric Touch",
  "Vicious Mockery",
  "Vision Of Elapsing Eons",
  "Vitriolic Sphere",
  "Vorpal Shot",
  "Vorpal Weapon",
  "Vortex Blast",
  "Wail Of The Banshee",
  "Wall of Fire",
  "Wall of Force",
  "Wall of Ice",
  "Wall of Stone",
  "Wall of Thorns",
  "Wardaway",
  "Warding Bond",
  "Water Breathing",
  "Water Bullet",
  "Water Walk",
  "Waves Of Exhaustion",
  "Web",
  "Weird",
  "Wind Cutter",
  "Wind Walk",
  "Wind Wall",
  "Wish",
  "Wither And Bloom",
  "Word of Radiance",
  "Word of Recall",
  "Wrathful Smite",
  "Zephyr Strike",
  "Zone Of Aimicability",
  "Zone of Truth",
] as const

/** Default card art keyed by exact spell name (includes non-SRD names for import matching). */
export const BUNDLED_SPELL_CARD_IMAGES_BY_NAME: Record<string, string> = Object.fromEntries(
  BUNDLED_SPELL_CARD_IMAGE_NAMES.map((name) => {
    const slug = SPELL_CARD_IMAGE_SLUG_OVERRIDES[name] ?? spellNameToCardImageSlug(name)
    return [name, spellCardImage(slug)]
  }),
)

export function defaultSpellCardImageUrl(
  spellName: string,
  options?: DefaultCardImageAvailability,
): string | null {
  return maybeFilterDefaultCardImageUrl(
    BUNDLED_SPELL_CARD_IMAGES_BY_NAME[spellName] ?? null,
    options?.requireAvailable !== false,
  )
}
