/** Standard tool names from the D&D 5.5e SRD / Player's Handbook. */
export const SRD_TOOL_NAMES = [
  "Alchemist's Supplies",
  "Brewer's Supplies",
  "Calligrapher's Supplies",
  "Carpenter's Tools",
  "Cartographer's Tools",
  "Cobbler's Tools",
  "Cook's Utensils",
  "Disguise Kit",
  "Forgery Kit",
  "Gaming Set",
  "Glassblower's Tools",
  "Herbalism Kit",
  "Jeweler's Tools",
  "Leatherworker's Tools",
  "Mason's Tools",
  "Musical Instrument",
  "Navigator's Tools",
  "Painter's Supplies",
  "Poisoner's Kit",
  "Potter's Tools",
  "Smith's Tools",
  "Thieves' Tools",
  "Tinker's Tools",
  "Vehicles (Land)",
  "Vehicles (Water)",
  "Weaver's Tools",
  "Woodcarver's Tools",
] as const
