#!/usr/bin/env node
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const gitPath = spawnSync("git", ["rev-parse", "--git-path", "hooks"], {
  cwd: root,
  encoding: "utf8",
})

if (gitPath.status !== 0) {
  console.log("Not a Git checkout; pre-push hook not installed.")
  process.exit(0)
}

const rawHookDir = gitPath.stdout.trim()
const hookDir = rawHookDir.startsWith("/") || /^[A-Za-z]:[\\/]/.test(rawHookDir)
  ? rawHookDir
  : join(root, rawHookDir)
const hookPath = join(hookDir, "pre-push")

mkdirSync(hookDir, { recursive: true })
writeFileSync(
  hookPath,
  `#!/bin/sh
# Generated by pnpm hooks:install. Version-controlled logic lives in
# scripts/verify-ci.mjs.
root="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
exec node "$root/scripts/verify-ci.mjs" --pre-push
`,
)
chmodSync(hookPath, 0o755)

if (!existsSync(hookPath)) {
  console.error(`Failed to install ${hookPath}`)
  process.exit(1)
}

console.log(`Installed full CI pre-push gate: ${hookPath}`)
